spring:
  application:
    name: eureka-server

---
spring:
  config:
    activate:
      on-profile: dev
    import: "optional:configserver:http://localhost:10482"

---
spring:
  config:
    activate:
      on-profile: prod,blue,green
    import: "configserver:http://team5-config-server:8888"
