spring:
  application:
    name: eureka-server

  profiles:
    active: dev
    include: local

  config:
    import: "optional:configserver:http://localhost:10482"

---

spring:
  config:
    activate:
      on-profile: prod,blue,green # 쉼표로 구분
    import: "configserver:http://config_server:8888"