name: Eureka_Server 배포

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  deploy-eureka:
    uses: nhnacademy-be12-high-five/.github/.github/workflows/infra-workflow.yml@main
    with:
      service-name: eureka_server
      container-name: team5-eureka-server
      compose-file: docker-compose.yml   # 필요 시 지정
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SSH_IP: ${{ secrets.SSH_IP }}
      SSH_ID: ${{ secrets.SSH_ID }}
      SSH_PW: ${{ secrets.SSH_PW }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
